version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      # - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=StudentManagerDb;User ID=sa;Password=sa@123;TrustServerCertificate=True;
      - ConnectionStrings__DefaultConnection=Server=studentmanager.cpe0cy0uu3ri.ap-southeast-2.rds.amazonaws.com,1433;Database=DBTest;User ID=admin;Password=B2ik5wqX8BNIKo6;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Sa@123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
